services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sorting_app
    volumes:
      - .:/app
    depends_on:
      - jaeger
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_SERVICE_NAME=SortingAlgorithms
      - OTEL_RESOURCE_ATTRIBUTES=service.version=1.0.0,deployment.environment=development

  jaeger:
    image: jaegertracing/jaeger:latest
    mem_limit: 2g
    mem_reservation: 512m
    container_name: jaeger
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "6832:6832/udp"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - SPAN_STORAGE_TYPE=memory